# Image officielle PHP 7.4 avec Apache
FROM php:7.4-apache

# Copier ton projet dans le serveur Apache
COPY . /var/www/html/

# Activer rewrite (utile pour les URLs propres)
RUN a2enmod rewrite

# Permissions correctes
RUN chown -R www-data:www-data /var/www/html

# Port exposé (optionnel mais propre)
EXPOSE 80