FROM php:7.4-apache

# Installer l'extension mysqli
RUN docker-php-ext-install mysqli

# Copier le projet
COPY . /var/www/html/

# Activer rewrite
RUN a2enmod rewrite

# Permissions
RUN chown -R www-data:www-data /var/www/html